find_path(jemalloc_INCLUDE_DIR jemalloc/jemalloc.h)
find_library(jemalloc_LIBRARY jemalloc)

if (jemalloc_INCLUDE_DIR AND jemalloc_LIBRARY)
  set(jemalloc_FOUND TRUE CACHE BOOL "" FORCE)
  add_library(jemalloc INTERFACE)
  target_include_directories(jemalloc INTERFACE ${jemalloc_INCLUDE_DIR})
  target_link_libraries(jemalloc INTERFACE ${jemalloc_LIBRARY})
  message(STATUS "Found jemalloc: ${jemalloc_LIBRARY}")
else()
  if(jemalloc_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find jemalloc")
  else()
    message(STATUS "Could not find jemalloc")
  endif()
endif()
