find_path(PCRE_INCLUDE NAMES pcre.h)
find_library(PCRE_LIBRARY NAMES libpcre.a libpcre.dylib libpcre.so)

if(PCRE_INCLUDE AND PCRE_LIBRARY)
  set(PCRE_FOUND YES CACHE BOOL "" FORCE)
  add_library(pcre INTERFACE)
  target_include_directories(pcre INTERFACE ${PCRE_INCLUDE})
  target_link_libraries(pcre INTERFACE ${PCRE_LIBRARY})
  message(STATUS "Found pcre: ${PCRE_LIBRARY}")
else()
  if(PCRE_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find pcre")
  else()
    message(STATUS "Could not find pcre")
  endif()
endif()
