find_path(libunwind_INCLUDE_DIR NAMES libunwind.h)
find_library(libunwind_LIBRARY NAMES libunwind.a libunwind.dylib libunwind.so)

if(libunwind_INCLUDE_DIR AND libunwind_LIBRARY)
  set(libunwind_FOUND YES CACHE BOOL "" FORCE)
  add_library(libunwind INTERFACE)
  target_include_directories(libunwind INTERFACE ${libunwind_INCLUDE_DIR})
  target_link_libraries(libunwind INTERFACE ${libunwind_LIBRARY})
  message(STATUS "Found libunwind ${libunwind_LIBRARY}")
else()
  if(libunwind_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find libunwind")
  else()
    message(STATUS "Could not find libunwind")
  endif()
endif()
